### ISSUE TITLE
Seleccionar un producto para ingresar al carrito

### ISSUE THREAD

**Issue by earias08** [ColmanNicolas/FrontendProyecto3#37]
Proceso
Cuando al menú de platos y seleccionamos un producto para cargar en el carrito

Resultado esperado
Visualizar un cartel que diga si efectivamente se pudo cargar el producto dentro del carrito.

Resultado actual
Se puede agregar el producto en el carrito sin problemas, pero no se visualiza nada que le diga al usuario si se cargo el producto. Se sugiere agregar una notificacion que le diga al usuario si se pudo o no agregar el producto.

Captura
![image](https://github.com/ColmanNicolas/FrontendProyecto3/assets/18445151/c2768f81-c879-408a-a515-e56529dcc145)

**Comment by ColmanNicolas** [comment]
interfaz de usuario mejorada
![cambio en botones admin](https://github.com/ColmanNicolas/FrontendProyecto3/assets/142736858/da666a5e-7268-47cc-9adc-f701104f5ee5)
