### ISSUE TITLE
Correcciones en el login y registro

### ISSUE THREAD

**Issue by earias08** [ColmanNicolas/FrontendProyecto3#38]
Proceso
Cuando ingresamos al la página principal, hay dos opciones en el menú de login y registro

Resultado esperado
Al utilizar el login de esa página como administrador ingresar al sitio del admin, si ingreso como un cliente ingresar al panel correspondiente

Resultado actual
El formulario de login y registro de esa página principal no es para un administrador, es solo de clientes y el administrador inicia sesion desde otra página. Especificar con un titulo o algun mensaje que ese formulario es solo para los clientes y en el login que si pueden ingresar los administradores tambien especificarlo con un titulo o mensaje

Captura
![image](https://github.com/ColmanNicolas/FrontendProyecto3/assets/18445151/4ae5330e-2fb8-4f2c-948d-24e8b40b450d)
![image](https://github.com/ColmanNicolas/FrontendProyecto3/assets/18445151/f5a0a911-ecb6-4885-b3df-de4aa788d364)
![image](https://github.com/ColmanNicolas/FrontendProyecto3/assets/18445151/d5e4fd2a-af8f-40aa-8aca-a631b139fdf6)

**Comment by ColmanNicolas** [comment]
Se cambio la vista del navbar desde Home
![Home con nuevo navbar](https://github.com/ColmanNicolas/FrontendProyecto3/assets/142736858/d651e5a6-797f-4ded-8922-560ca8f93ad6)

Se agregó aclaración en el formulario de registro de que solo es para registro de clientes
![register nuevo](https://github.com/ColmanNicolas/FrontendProyecto3/assets/142736858/09b1d40e-1342-4602-a4d2-1d257c840e9f)
