### ISSUE TITLE
Error al cerrar sesion.

### ISSUE THREAD

**Issue by earias08** [ColmanNicolas/FrontendProyecto3#39]
Proceso
Al cerrar sesion desde la pagina del administrador

Resultado esperado
Visualizar un mensaje indicando que la sesion se cerro con exito.

Resultado actual
se redirecciona correctamente a la web del login, pero al precionar la opción volver a home, nuevamente opción home en la siguiente pantalla adjunta, se visualiza la página principal y se ve la opción de cerrar sesion nuevamente.

Captura
![image](https://github.com/ColmanNicolas/FrontendProyecto3/assets/18445151/09d30079-456c-45de-998f-e1b7f2d50ba6)
![image](https://github.com/ColmanNicolas/FrontendProyecto3/assets/18445151/105da825-772f-4cec-87cc-47be63428e4a)
![image](https://github.com/ColmanNicolas/FrontendProyecto3/assets/18445151/0f52f372-ee43-4028-88e9-e1e58784319b)
![image](https://github.com/ColmanNicolas/FrontendProyecto3/assets/18445151/cc1b2486-f892-47d6-8163-9cd6cb44d0d5)

**Comment by ColmanNicolas** [comment]
Se agrego mensaje de cierre de sesion y se hizo mas intuitivo el camino para volver al landing-page y posteriormetne poder volver al home
![cambio en botones admin](https://github.com/ColmanNicolas/FrontendProyecto3/assets/142736858/c77d6951-2d94-413e-9a5f-6a22cfebadf6)
