### ISSUE TITLE
Error al registrar un usuario

### ISSUE THREAD

**Issue by earias08** [ColmanNicolas/FrontendProyecto3#40]
Proceso
Al ingresar a la página del administrador, y completar los datos de registro de usuario.

Resultado esperado
Visualizar un mensaje que indique si se pudo crear una cuenta o no.

Resultado actual
Nos redirecciona a la página del login, pero no se sabe si se pudo crear o no la cuenta nueva.

Captura
![image](https://github.com/ColmanNicolas/FrontendProyecto3/assets/18445151/9d89e51d-d52b-4df7-9179-db3d3850c761)
![image](https://github.com/ColmanNicolas/FrontendProyecto3/assets/18445151/55888ed3-0b7f-4757-b1ce-32d952f75714)

**Comment by ColmanNicolas** [comment]
Se agregaron mensajes en ventanas emergentes para confirmar un registro exitoso o mostrar un registro fallido

![mensaje de register](https://github.com/ColmanNicolas/FrontendProyecto3/assets/142736858/a8a46a14-eb71-4e63-b2a1-8718cd19955f)



![mensaje de error en register](https://github.com/ColmanNicolas/FrontendProyecto3/assets/142736858/4e6a8fe1-4513-4833-9937-d1c43fab61a3)
