### ISSUE TITLE
Correcciones para habilitar un usuario

### ISSUE THREAD

**Issue by earias08** [ColmanNicolas/FrontendProyecto3#41]
Proceso
Cuando nos logueamos como administradores

Resultado esperado
Visualizar la tabla de administración de usuario, para activar o desactivar un usuario

Resultado actual
La tabla actual, no tiene un botón intuitivo que indique que al presionarlo se habilita el usuario, cambiaria el icono de configuración que se visualiza en la columna habilitación, o agregaria un tooltip que indique al usuario que al presionarlo se puede habilitar o deshabilitar. Luego la opción de información no muestra ningun dato, si aún no se desarrollo esa opción pueden dejarlo como un botón deshabilitado o quitarlo de la tabla.

Captura
![image](https://github.com/ColmanNicolas/FrontendProyecto3/assets/18445151/3896fa6f-e979-432d-909a-84afefc8662e)

**Comment by ColmanNicolas** [comment]
Se deshabilitaron los botones de informacion que todavia no estan desarrollados en el codigo y se hizo un poco mas intuitivo la habilitacion / deshabilitacion de usuarios 
![cambio en botones admin](https://github.com/ColmanNicolas/FrontendProyecto3/assets/142736858/15222ba4-63fe-4b62-bd46-21625be7f422)
