### ISSUE TITLE
Modificar mensajes de validación en formulario de pago de servicio

### ISSUE THREAD

**Issue by earias08** [ColmanNicolas/FrontendProyecto3#42]
Proceso
Cuando ingresamos al formulario para pagar el servicio.

Resultado esperado
visualziar el formulario para pagar

Resultado actual
indicar que la fecha de vencimiento de la tarjeta esta actualmente en formato mm/dd

Captura
![image](https://github.com/ColmanNicolas/FrontendProyecto3/assets/18445151/c74763af-81e6-4772-b34a-a32b2d7e6bc0)

**Comment by ColmanNicolas** [comment]
Corregido el formato y su aclaracion para el usuario
