### ISSUE TITLE
Error al actualizar un pedido del menú

### ISSUE THREAD

**Issue by earias08** [ColmanNicolas/FrontendProyecto3#48]
Proceso
Al loguearse en el servicio de gestion de menú

Resultado esperado
modificar los datos de las opciones del menú o borrar un item de menú, ver un cartel indicando si el cambio se realizo o el producto se borro correctamente, luego visualizar los cambios en la tabla que contiene todas las opciones de menú.

Resultado actual
Luego de modificar el precio o nombre del menú, no se observa ninguna advertencia para el usuario, ademas este cambio no se visualiza automaticamente en la tabla de productos, se debe actualizar manualmente la página para ver el cambio.

Captura
![image](https://github.com/ColmanNicolas/FrontendProyecto3/assets/18445151/82b6b1c8-4715-43ba-b2c9-892726d50d81)
![image](https://github.com/ColmanNicolas/FrontendProyecto3/assets/18445151/7cbcb27b-b18f-4233-9640-6636f8b70c78)

**Comment by ColmanNicolas** [comment]
Corrección de actualizacion visual al modificar un platode menu
![modPrecio](https://github.com/ColmanNicolas/FrontendProyecto3/assets/142736858/e243bb39-3258-4b26-9982-2f751fa3a87e)
Ahora al modificar se ve el plato se recibe una notificacion,(**indice 2**) del plato que fue modificado.
Tambien se visualizará en el listado unicamente el plato modificado, quedando a voluntad del usuario recargar el listado( **indice 1**), filtrar el listado o hacer una nueva busqueda de un plato
![modPrecioResultado](https://github.com/ColmanNicolas/FrontendProyecto3/assets/142736858/9db5ff25-ab55-4c9d-9e10-f54f27acc774)
