### ISSUE TITLE
La issue: Error al actualizar un pedido del menú #48 esta incompleta

### ISSUE THREAD

**Issue by earias08** [ColmanNicolas/FrontendProyecto3#53]
Cuando eliminamos un producto del menú "crear productos" este cambio no se ve reflejado tampoco hay un  mensaje intuitivo para el usuario, sino que el usuario debe refrescar manualmente la página para saber que sucedio.
En la issue cerrada [detalle issue anterior](https://github.com/ColmanNicolas/FrontendProyecto3/issues/48) el error mencionado se da al actualizar y borrar. Por lo tanto queda pendiente realizar la correccion.

**Comment by ColmanNicolas** [comment]
Eliminación de un menu creado: 


![mod previo](https://github.com/user-attachments/assets/85d1cfd9-ba31-42a9-82ab-c1314b2cbbce)


Como resultado de borrar se muestra un cartel de que el plato fue borrado con exito y el listado de menus se recarga automaticamente

![mod resul](https://github.com/user-attachments/assets/6f08d5d5-a50a-4a33-ac74-c22d1dc2f623)
